"""phase2_schema_updates

Revision ID: 656443275ac8
Revises: 'v3_phase1_drop_unused'
Create Date: 2026-08-11 08:27:01.457091+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '656443275ac8'
down_revision: Union[str, None] = 'v3_phase1_drop_unused'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_definitions', sa.Column('generator_tello', sa.Text(), nullable=True))
    op.add_column('block_definitions', sa.Column('module_category', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_block_definitions_module_category'), 'block_definitions', ['module_category'], unique=False)
    op.add_column('device_profiles', sa.Column('device_category', sa.String(length=30), nullable=True))
    op.add_column('device_profiles', sa.Column('udp_port', sa.Integer(), nullable=True))
    op.add_column('learning_modules', sa.Column('block_category', sa.String(length=50), nullable=True))
    op.drop_column('learning_modules', 'xp_reward')
    op.add_column('projects', sa.Column('module_category', sa.String(length=50), nullable=True))
    op.drop_column('user_progress', 'xp_earned')
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS ck_users_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_users_role'), 'users', "role::text = ANY (ARRAY['user'::character varying, 'siswa'::character varying, 'guru'::character varying, 'admin'::character varying]::text[])")
    op.add_column('user_progress', sa.Column('xp_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('projects', 'module_category')
    op.add_column('learning_modules', sa.Column('xp_reward', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    op.drop_column('learning_modules', 'block_category')
    op.drop_column('device_profiles', 'udp_port')
    op.drop_column('device_profiles', 'device_category')
    op.drop_index(op.f('ix_block_definitions_module_category'), table_name='block_definitions')
    op.drop_column('block_definitions', 'module_category')
    op.drop_column('block_definitions', 'generator_tello')
    # ### end Alembic commands ###
