"""Add STEM fields to Project

Revision ID: 06b10cd9f1f4
Revises: 'e85ce4ed7cda'
Create Date: 2026-08-03 03:49:49.274591+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '06b10cd9f1f4'
down_revision: Union[str, None] = 'e85ce4ed7cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('target_hardware_type', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('execution_target', sa.String(length=50), server_default='hardware', nullable=False))
    op.add_column('projects', sa.Column('subject_context', sa.String(length=50), server_default='coding', nullable=False))
    op.alter_column('projects', 'generated_code',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="NULL",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'generated_code',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('projects', 'subject_context')
    op.drop_column('projects', 'execution_target')
    op.drop_column('projects', 'target_hardware_type')
    # ### end Alembic commands ###
