"""add blynk_config_json to projects

Revision ID: 60af5e678a38
Revises: '006312965dfc'
Create Date: 2026-08-05 03:18:44.701146+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '60af5e678a38'
down_revision: Union[str, None] = '006312965dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('blynk_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'blynk_config_json')
    # ### end Alembic commands ###
