"""add photo_url to users

Revision ID: 006312965dfc
Revises: '06b10cd9f1f4'
Create Date: 2026-08-04 06:04:38.430326+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '006312965dfc'
down_revision: Union[str, None] = '06b10cd9f1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
