"""add Hardwarelog table without JSONB

Revision ID: e85ce4ed7cda
Revises: '002_database_overhaul'
Create Date: 2026-07-31 04:23:43.916316+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e85ce4ed7cda'
down_revision: Union[str, None] = '002_database_overhaul'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_profile_id', sa.UUID(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('log_message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_profile_id'], ['device_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_logs_device_profile_id'), 'hardware_logs', ['device_profile_id'], unique=False)
    op.drop_constraint(op.f('block_definitions_block_type_key'), 'block_definitions', type_='unique')
    op.drop_index(op.f('ix_block_definitions_block_type'), table_name='block_definitions')
    op.create_index(op.f('ix_block_definitions_block_type'), 'block_definitions', ['block_type'], unique=True)
    op.create_index(op.f('ix_device_profiles_owner_id'), 'device_profiles', ['owner_id'], unique=False)
    op.drop_constraint(op.f('hardware_types_name_key'), 'hardware_types', type_='unique')
    op.drop_index(op.f('ix_hardware_types_name'), table_name='hardware_types')
    op.create_index(op.f('ix_hardware_types_name'), 'hardware_types', ['name'], unique=True)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.drop_constraint(op.f('user_gamification_user_id_key'), 'user_gamification', type_='unique')
    op.drop_index(op.f('ix_user_gamification_user_id'), table_name='user_gamification')
    op.create_index(op.f('ix_user_gamification_user_id'), 'user_gamification', ['user_id'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_gamification_user_id'), table_name='user_gamification')
    op.create_index(op.f('ix_user_gamification_user_id'), 'user_gamification', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_gamification_user_id_key'), 'user_gamification', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_hardware_types_name'), table_name='hardware_types')
    op.create_index(op.f('ix_hardware_types_name'), 'hardware_types', ['name'], unique=False)
    op.create_unique_constraint(op.f('hardware_types_name_key'), 'hardware_types', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_device_profiles_owner_id'), table_name='device_profiles')
    op.drop_index(op.f('ix_block_definitions_block_type'), table_name='block_definitions')
    op.create_index(op.f('ix_block_definitions_block_type'), 'block_definitions', ['block_type'], unique=False)
    op.create_unique_constraint(op.f('block_definitions_block_type_key'), 'block_definitions', ['block_type'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_hardware_logs_device_profile_id'), table_name='hardware_logs')
    op.drop_table('hardware_logs')
    # ### end Alembic commands ###
