"""Add STEM fields to Project

Revision ID: 3e8afcfaf4f6
Revises: '656443275ac8'
Create Date: 2026-08-11 09:47:57.668523+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3e8afcfaf4f6'
down_revision: Union[str, None] = '656443275ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
