import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/services/device_connection_service.dart';
import '../../data/data_sources/device_api_service.dart';
import '../../data/models/device_profile_model.dart';
import '../../../auth/data/data_sources/auth_storage_service.dart';

import '../widgets/device_selection_modal.dart';
import '../widgets/wifi_connection_modal.dart';
import '../widgets/device_details_modal.dart';
import '../widgets/saved_device_card.dart';

class DeviceConnectionScreen extends StatefulWidget {
  final bool showBackButton;

  const DeviceConnectionScreen({super.key, this.showBackButton = false});

  @override
  State<DeviceConnectionScreen> createState() => _DeviceConnectionScreenState();
}

class _DeviceConnectionScreenState extends State<DeviceConnectionScreen> {
  final TextEditingController _searchController = TextEditingController();

  List<DeviceProfileModel> _savedDevices = [];
  bool _isLoadingDevices = true;
  String? _connectingDeviceId;

  @override
  void initState() {
    super.initState();
    DeviceConnectionService.instance.loadPairedDevices(silent: true);
    _loadSavedDevices();
  }

  Future<void> _loadSavedDevices() async {
    setState(() => _isLoadingDevices = true);
    try {
      final devices = await DeviceApiService().getDevices();
      setState(() {
        _savedDevices = devices;
        _isLoadingDevices = false;
      });
    } catch (e) {
      if (mounted) {
        setState(() => _isLoadingDevices = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Gagal memuat perangkat tersimpan: $e')),
        );
      }
    }
  }

  Future<void> _saveDevice(
    String label,
    String protocol, {
    String? macAddress,
    String? host,
    int? port,
  }) async {
    try {
      final userId = AuthStorageService().currentUser?.id ?? '';
      final newDevice = DeviceProfileModel(
        id: '', // Will be generated by backend
        ownerId: userId,
        label: label,
        protocol: protocol,
        useTls: false,
        macAddress: macAddress,
        host: host,
        port: port,
        createdAt: DateTime.now(),
      );
      final profile = await DeviceApiService().createDevice(newDevice);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Berhasil menyimpan: ${profile.label}'),
            backgroundColor: Colors.green,
          ),
        );
      }
      _loadSavedDevices();
    } catch (e) {
      debugPrint("Gagal menyimpan device ke database: $e");
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Gagal menyimpan: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  Future<void> _connectToDevice(DeviceProfileModel device, DeviceConnectionService service) async {
    // Putuskan koneksi yang ada jika sedang nyambung ke device lain
    if (service.isConnected || service.isConnecting) {
      service.disconnect();
      await Future.delayed(
        const Duration(milliseconds: 200),
      ); // Beri waktu cleanup
    }

    final isBluetooth = device.protocol == 'bluetooth';

    if (isBluetooth && device.macAddress != null) {
      service.setConnectionMode(ConnectionMode.bluetooth);
      setState(() => _connectingDeviceId = device.id);
      await service.connectBluetoothByMac(device.macAddress!, deviceId: device.id);
      if (mounted) {
        setState(() => _connectingDeviceId = null);
        if (!service.isConnected) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(service.statusMessage),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    } else if (!isBluetooth && device.host != null) {
      service.setConnectionMode(ConnectionMode.wifi);
      setState(() => _connectingDeviceId = device.id);
      await service.connectWifi(
        device.host!,
        device.port?.toString() ?? '',
        deviceId: device.id,
      );
      if (mounted) {
        setState(() => _connectingDeviceId = null);
        if (!service.isConnected) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(service.statusMessage),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return ListenableBuilder(
      listenable: DeviceConnectionService.instance,
      builder: (context, _) {
        final service = DeviceConnectionService.instance;
        final isBluetoothMode =
            service.connectionMode == ConnectionMode.bluetooth;

        final primaryColor = isBluetoothMode
            ? const Color(0xFF2A5EE8)
            : const Color(0xFFF79E66);
        final unselectedIconColor = Colors.grey.shade400;

        // Sort devices: Online first
        List<DeviceProfileModel> sortedDevices = List.from(_savedDevices);
        sortedDevices.sort((a, b) {
          final isAOnline =
              (a.protocol == 'bluetooth' &&
                  service.isConnected &&
                  service.connectionMode == ConnectionMode.bluetooth &&
                  service.selectedDevice?.address == a.macAddress) ||
              (a.protocol == 'websocket' &&
                  service.isConnected &&
                  service.connectionMode == ConnectionMode.wifi &&
                  service.connectedIp == a.host);
          final isBOnline =
              (b.protocol == 'bluetooth' &&
                  service.isConnected &&
                  service.connectionMode == ConnectionMode.bluetooth &&
                  service.selectedDevice?.address == b.macAddress) ||
              (b.protocol == 'websocket' &&
                  service.isConnected &&
                  service.connectionMode == ConnectionMode.wifi &&
                  service.connectedIp == b.host);
          if (isAOnline && !isBOnline) return -1;
          if (!isAOnline && isBOnline) return 1;
          return 0;
        });

        // Filter based on search
        final query = _searchController.text.toLowerCase();
        if (query.isNotEmpty) {
          sortedDevices = sortedDevices
              .where(
                (d) =>
                    d.label.toLowerCase().contains(query) ||
                    (d.macAddress != null &&
                        d.macAddress!.toLowerCase().contains(query)) ||
                    (d.host != null && d.host!.toLowerCase().contains(query)),
              )
              .toList();
        }

        return Scaffold(
          backgroundColor: const Color(0xFFF4F7FB),
          body: SafeArea(
            bottom: false,
            child: Padding(
              padding: const EdgeInsets.fromLTRB(24, 24, 24, 0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      if (widget.showBackButton)
                        Padding(
                          padding: const EdgeInsets.only(right: 16.0),
                          child: InkWell(
                            onTap: () => context.pop(),
                            child: const Icon(
                              Icons.arrow_back_ios,
                              color: Color(0xFF003092),
                              size: 20,
                            ),
                          ),
                        ),
                      const Text(
                        'My Devices',
                        style: TextStyle(
                          fontSize: 24,
                          fontWeight: FontWeight.w900,
                          color: Color(0xFF003092),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 24),

                  // Connect New Device Card
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(24),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withValues(alpha: 0.03),
                          blurRadius: 10,
                          offset: const Offset(0, 4),
                        ),
                      ],
                    ),
                    child: Row(
                      children: [
                        // Vertical Toggle
                        Container(
                          padding: const EdgeInsets.symmetric(
                            vertical: 8,
                            horizontal: 8,
                          ),
                          decoration: BoxDecoration(
                            color: const Color(0xFFF4F7FB),
                            borderRadius: BorderRadius.circular(30),
                          ),
                          child: Column(
                            children: [
                              GestureDetector(
                                onTap: () => service.setConnectionMode(
                                  ConnectionMode.bluetooth,
                                ),
                                child: Container(
                                  width: 40,
                                  height: 40,
                                  decoration: BoxDecoration(
                                    color: isBluetoothMode
                                        ? primaryColor
                                        : Colors.transparent,
                                    shape: BoxShape.circle,
                                  ),
                                  child: Icon(
                                    Icons.bluetooth,
                                    color: isBluetoothMode
                                        ? Colors.white
                                        : unselectedIconColor,
                                    size: 20,
                                  ),
                                ),
                              ),
                              const SizedBox(height: 8),
                              GestureDetector(
                                onTap: () => service.setConnectionMode(
                                  ConnectionMode.wifi,
                                ),
                                child: Container(
                                  width: 40,
                                  height: 40,
                                  decoration: BoxDecoration(
                                    color: !isBluetoothMode
                                        ? primaryColor
                                        : Colors.transparent,
                                    shape: BoxShape.circle,
                                  ),
                                  child: Icon(
                                    Icons.wifi,
                                    color: !isBluetoothMode
                                        ? Colors.white
                                        : unselectedIconColor,
                                    size: 20,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 16),
                        // Content
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text(
                                'Connect New Device',
                                style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w800,
                                  color: Color(0xFF0A122C),
                                ),
                              ),
                              const SizedBox(height: 4),
                              Text(
                                'Ready to pair a new hardware kit to your workspace.',
                                style: TextStyle(
                                  fontSize: 12,
                                  color: Colors.grey.shade600,
                                  height: 1.4,
                                ),
                              ),
                              const SizedBox(height: 12),
                              SizedBox(
                                width: double.infinity,
                                height: 40,
                                child: ElevatedButton(
                                  onPressed:
                                      (service.isConnecting &&
                                          _connectingDeviceId == null)
                                      ? null
                                      : (isBluetoothMode
                                            ? () => showDeviceSelectionModal(context, onDeviceSaved: _saveDevice)
                                            : () => showWifiConnectionModal(context, onDeviceSaved: _saveDevice)),
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: primaryColor,
                                    foregroundColor: Colors.white,
                                    elevation: 0,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                  ),
                                  child:
                                      (service.isConnecting &&
                                          _connectingDeviceId == null)
                                      ? const SizedBox(
                                          width: 16,
                                          height: 16,
                                          child: CircularProgressIndicator(
                                            color: Colors.white,
                                            strokeWidth: 2,
                                          ),
                                        )
                                      : Text(
                                          isBluetoothMode
                                              ? 'Connect via Bluetooth'
                                              : 'Connect via Wi-Fi',
                                          style: const TextStyle(
                                            fontWeight: FontWeight.bold,
                                            fontSize: 13,
                                          ),
                                        ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: 24),

                  // Saved Devices Header
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'Saved Devices',
                        style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.w900,
                          color: Color(0xFF003092),
                        ),
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 10,
                          vertical: 4,
                        ),
                        decoration: BoxDecoration(
                          color: const Color(0xFFE8F0FE),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Text(
                          '${_savedDevices.length} kit',
                          style: const TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF005CFF),
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // Search Bar
                  Container(
                    height: 44,
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: Colors.grey.shade200),
                    ),
                    child: TextField(
                      controller: _searchController,
                      onChanged: (v) => setState(() {}),
                      decoration: InputDecoration(
                        hintText: 'Cari perangkat...',
                        hintStyle: TextStyle(
                          color: Colors.grey.shade400,
                          fontSize: 14,
                        ),
                        prefixIcon: Icon(
                          Icons.search,
                          color: Colors.grey.shade400,
                          size: 20,
                        ),
                        border: InputBorder.none,
                        contentPadding: const EdgeInsets.symmetric(
                          vertical: 12,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),

                  // List view
                  Expanded(
                    child: _isLoadingDevices
                        ? const Center(child: CircularProgressIndicator())
                        : sortedDevices.isEmpty
                        ? Center(
                            child: Text(
                              'Tidak ada perangkat yang tersimpan.',
                              style: TextStyle(color: Colors.grey.shade500),
                            ),
                          )
                        : ListView.builder(
                            padding: const EdgeInsets.only(bottom: 120),
                            physics: const BouncingScrollPhysics(),
                            itemCount: sortedDevices.length,
                            itemBuilder: (context, index) {
                              final device = sortedDevices[index];
                              return SavedDeviceCard(
                                device: device,
                                service: service,
                                isConnecting: _connectingDeviceId == device.id,
                                onTap: () => _connectToDevice(device, service),
                                onDisconnect: () => service.disconnect(),
                                onShowDetails: () => showDeviceDetailsModal(
                                  context,
                                  device,
                                  onDeviceUpdatedOrDeleted: _loadSavedDevices,
                                ),
                              );
                            },
                          ),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}
