from uuid import UUID
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from fastapi import HTTPException, status
from app.modules.school.models import School
from app.modules.users.models import User

async def verify_invite_token(token: str) -> School | None:
    """
    Mock function to verify an invite token.
    In a real app, this would query an InviteToken table.
    For now, we'll assume a dummy implementation or that it returns a dummy school
    or checks against a hardcoded pattern if you have specific requirements.
    
    If the token is "INVALID", we return None.
    If the token is valid, we'll just return the first school in the DB (for demonstration).
    """
    if token == "INVALID" or not token:
        return None
    # For now, let's just return a placeholder or wait for DB implementation.
    return None # We need the DB session to actually query, so we'll pass it in resolve_role_and_school

async def resolve_role_and_school(db: AsyncSession, user_id: UUID, role: str, invite_token: str) -> User:
    """
    Resolves and updates the user's role and school_id based on the provided invite token.
    """
    if role not in ["siswa", "guru"]:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid role specified.")
    
    # Simple token verification mock
    if not invite_token or len(invite_token) < 5:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid invite token.")
        
    # Get the first school (for demo purposes) or create one if none exists
    result = await db.execute(select(School).limit(1))
    school = result.scalar_one_or_none()
    
    if not school:
        school = School(name="Default School", address="Generated by system")
        db.add(school)
        await db.commit()
        await db.refresh(school)
        
    # Update user
    user_result = await db.execute(select(User).where(User.id == user_id))
    user = user_result.scalar_one_or_none()
    
    if not user:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found.")
        
    user.role = role
    user.school_id = school.id
    user.onboarding_source = "invite_token"
    
    await db.commit()
    await db.refresh(user)
    
    return user
